const busdata = [
    { busname: "Zingbus", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "04:05", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "4.5", price: 620 },
    { busname: "Vikas Travels Jaipur", bustype: "A/C Seater/Sleeper", Depature: "20:45", arrival: "05:30", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "4.2", price: 530 },
    { busname: "Rahi Travells", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "04:05", pickup: "Chandni Chowk", drop: "private bus stop", seats: 26, rating: "4.5", price: 680 },
    { busname: "Shrinath Solitaire Premium Class", bustype: "A/C Seater/Sleeper", Depature: "21:20", arrival: "04:05", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "4.8", price: 980 },
    { busname: "Mahalaxmi Travels ISO", bustype: "A/C Seater/Sleeper", Depature: "20:45", arrival: "06:00", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "4.9", price: 450 },
    { busname: "RC Travels", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "04:05", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "4.5", price: 750 },
    { busname: "Goldline Super Deluxe", bustype: "A/C Seater/Sleeper", Depature: "21:20", arrival: "05:30", pickup: "Chandni Chowk", drop: "private bus stop", seats: 26, rating: "4.5", price: 450 },
    { busname: "Goldline Super Deluxe", bustype: "A/C Seater/Sleeper", Depature: "21:20", arrival: "06:00", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "4.5", price: 650 },
    { busname: "Vijay Tour and Travels", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "05:30", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "4.6", price: 250 },
    { busname: "Zingbus", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "04:05", pickup: "Chandni Chowk", drop: "private bus stop", seats: 26, rating: "4.5", price: 680 },
    { busname: "Vijay Tour and Travels", bustype: "A/C Seater/Sleeper", Depature: "21:20", arrival: "05:30", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "3.5", price: 950 },
    { busname: "Deepak Transport Company", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "06:00", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "4.5", price: 980 },
    { busname: "Samreen Travels", bustype: "A/C Seater/Sleeper", Depature: "21:20", arrival: "04:05", pickup: "Chandni Chowk", drop: "private bus stop", seats: 26, rating: "4.5", price: 852 },
    { busname: "Samreen Travels", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "04:05", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "2.5", price: 455 },
    { busname: "Mahalaxmi Travels ISO", bustype: "A/C Seater/Sleeper", Depature: "21:20", arrival: "06:00", pickup: "Chandni Chowk", drop: "private bus stop", seats: 26, rating: "4.5", price: 852 },
    { busname: "Mahalaxmi Travels ISO", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "05:30", pickup: "Karol Bagh", drop: "private bus stop", seats: 26, rating: "4.5", price: 654 },
    { busname: "Goldline Super Deluxe", bustype: "A/C Seater/Sleeper", Depature: "20:45", arrival: "06:00", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "4.5", price: 250 },
    { busname: "Babu Travels", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "04:05", pickup: "Karol Bagh", drop: "private bus stop", seats: 26, rating: "4.5", price: 680 },
    { busname: "Goldline Super Deluxe", bustype: "A/C Seater/Sleeper", Depature: "21:20", arrival: "05:30", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "3.5", price: 456 },
    { busname: "Babu Travels", bustype: "A/C Seater/Sleeper", Depature: "21:20", arrival: "04:05", pickup: "Karol Bagh", drop: "private bus stop", seats: 26, rating: "4.5", price: 660 },
    { busname: "Gulzar Tours and Travels", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "06:00", pickup: "Karol Bagh", drop: "private bus stop", seats: 26, rating: "4.5", price: 680 },
    { busname: "Chanakya Travels Agency", bustype: "A/C Seater/Sleeper", Depature: "20:45", arrival: "06:00", pickup: "Kashmiri Gate", drop: "private bus stop", seats: 26, rating: "4.5", price: 654 },
    { busname: "Gulzar Tours and Travels", bustype: "A/C Seater/Sleeper", Depature: "21:20", arrival: "05:30", pickup: "Kashmiri Gate", drop: "private bus stop", seats: 26, rating: "4.5", price: 880 },
    { busname: "Chanakya Travels Agency", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "04:05", pickup: "Kashmiri Gate", drop: "private bus stop", seats: 26, rating: "4.5", price: 785 },
    { busname: "Gulzar Tours and Travels", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "06:00", pickup: "Karol Bagh", drop: "private bus stop", seats: 26, rating: "3.5", price: 562 },
    { busname: "Chanakya Travels Agency", bustype: "A/C Seater/Sleeper", Depature: "20:45", arrival: "05:30", pickup: "Kashmiri Gate", drop: "private bus stop", seats: 26, rating: "4.5", price: 680 },
    { busname: "Zingbus", bustype: "A/C Seater/Sleeper", Depature: "21:20", arrival: "04:05", pickup: "Kashmiri Gate", drop: "private bus stop", seats: 26, rating: "4.5", price: 751 },
    { busname: "Shakti Travels", bustype: "A/C Seater/Sleeper", Depature: "22:20", arrival: "06:00", pickup: "Kashmiri Gate", drop: "private bus stop", seats: 26, rating: "4.5", price: 542 },
    { busname: "Shakti Travels", bustype: "A/C Seater/Sleeper", Depature: "20:45", arrival: "05:30", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "4.5", price: 852 },
    { busname: "Shakti Travels", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "05:30", pickup: "Karol Bagh", drop: "private bus stop", seats: 26, rating: "4.5", price: 452 },
    { busname: "Deepak Transport Company", bustype: "A/C Seater/Sleeper", Depature: "22:20", arrival: "04:05", pickup: "Dhaula kuan metro station", drop: "private bus stop", seats: 26, rating: "4.5", price: 777 },
    { busname: "Gulzar Tour and Travels", bustype: "A/C Seater/Sleeper", Depature: "20:45", arrival: "06:00", pickup: "ISBT MATERO STATION GATE NO.2", drop: "private bus stop", seats: 26, rating: "4.5", price: 680 },
    { busname: "Gulzar Tour and Travels", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "05:30", pickup: "ISBT MATERO STATION GATE NO.2", drop: "private bus stop", seats: 26, rating: "4.5", price: 864 },
    { busname: "Nama Travels", bustype: "A/C Seater/Sleeper", Depature: "22:20", arrival: "04:05", pickup: "ISBT MATERO STATION GATE NO.2", drop: "private bus stop", seats: 26, rating: "4.5", price: 680 },
    { busname: "Nama Travels", bustype: "A/C Seater/Sleeper", Depature: "20:45", arrival: "06:00", pickup: "ISBT MATERO STATION GATE NO.2", drop: "private bus stop", seats: 26, rating: "4.5", price: 752 },
    { busname: "Nama Travels", bustype: "A/C Seater/Sleeper", Depature: "22:20", arrival: "05:30", pickup: "ISBT MATERO STATION GATE NO.2", drop: "private bus stop", seats: 26, rating: "4.5", price: 654 },
    { busname: "Shrinath Solitaire Premium Class", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "04:05", pickup: "ISBT MATERO STATION GATE NO.2", drop: "private bus stop", seats: 26, rating: "4.5", price: 680 },
    { busname: "Zingbus", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "05:30", pickup: "ISBT MATERO STATION GATE NO.2", drop: "private bus stop", seats: 26, rating: "4.5", price: 896 },
    { busname: "Shrinath Solitaire Premium Class", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "04:05", pickup: "New Delhi Railway Station", drop: "private bus stop", seats: 26, rating: "4.5", price: 896 },
    { busname: "Shrinath Solitaire Premium Class", bustype: "A/C Seater/Sleeper", Depature: "05:30", arrival: "04:05", pickup: "New Delhi Railway Station", drop: "private bus stop", seats: 26, rating: "4.5", price: 654 },
    { busname: "Babu Travels", bustype: "A/C Seater/Sleeper", Depature: "22:20", arrival: "06:00", pickup: "New Delhi Railway Station", drop: "private bus stop", seats: 26, rating: "4.5", price: 754 },
    { busname: "Shrinath Solitaire Premium Class", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "04:05", pickup: "New Delhi Railway Station", drop: "private bus stop", seats: 26, rating: "4.5", price: 680 },
    { busname: "Deepak Transport Company", bustype: "A/C Seater/Sleeper", Depature: "20:45", arrival: "04:05", pickup: "New Delhi Railway Station", drop: "private bus stop", seats: 26, rating: "4.5", price: 554 },
    { busname: "Babu Travels", bustype: "A/C Seater/Sleeper", Depature: "22:20", arrival: "05:30", pickup: "New Delhi Railway Station", drop: "private bus stop", seats: 26, rating: "4.5", price: 455 },
    { busname: "Babu Travels", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "06:00", pickup: "New Delhi Railway Station", drop: "private bus stop", seats: 26, rating: "4.5", price: 245 },
    { busname: "Babu Travels", bustype: "A/C Seater/Sleeper", Depature: "23:15", arrival: "06:00", pickup: "New Delhi Railway Station", drop: "private bus stop", seats: 26, rating: "4.5", price: 680 },
    { busname: "Deepak Transport Company", bustype: "A/C Seater/Sleeper", Depature: "22:20", arrival: "04:05", pickup: "New Delhi Railway Station", drop: "private bus stop", seats: 26, rating: "4.5", price: 680 },
    { busname: "Vijay Shakti Travels", bustype: "A/C Seater/Sleeper", Depature: "20:45", arrival: "04:05", pickup: "majnu ka teela", drop: "private bus stop", seats: 26, rating: "4.5", price: 856 },
    { busname: "Vijay Shakti Travels", bustype: "A/C Seater/Sleeper", Depature: "20:45", arrival: "05:30", pickup: "majnu ka teela", drop: "private bus stop", seats: 26, rating: "4.5", price: 754 },
    { busname: "Deepak Transport Company", bustype: "A/C Seater/Sleeper", Depature: "20:45", arrival: "05:30", pickup: "majnu ka teela", drop: "private bus stop", seats: 26, rating: "4.5", price: 856 },
]

